---
swagger: '2.0'
info:
  title: API V1
  version: v1
paths:
  "/api/v1/tags/{id}":
    get:
      summary: Get Tag
      tags:
      - Tag
      consumes:
      - application/json
      parameters:
      - name: id
        in: path
        type: integer
        required: true
      responses:
        '200':
          description: Tag Found
          schema:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
              created_at:
                type: string
              updated_at:
                type: string
