---
swagger: '2.0'
info:
  title: API V1
  version: v1
paths:
  "/api/customers/{id}":
    get:
      summary: Get Customer
      tags:
      - Customer
      consumes:
      - application/json
      parameters:
      - name: id
        in: path
        type: integer
        required: true
      responses:
        '200':
          description: Customer Found
          schema:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
              email:
                type: string
              type: object
              form:
                id:
                  type: integer
                name:
                  type: string
              created_at:
                type: string
    delete:
      summary: Delete Customer
      tags:
      - Customer
      consumes:
      - application/json
      parameters:
      - name: id
        in: path
        type: integer
        required: true
      responses:
        '204':
          description: Customers Deleted
  "/api/customers":
    get:
      summary: Get Customers
      tags:
      - Customer
      consumes:
      - application/json
      parameters:
      - name: page
        in: query
        type: integer
      responses:
        '200':
          description: Customers Found
          schema:
            type: object
            properties:
              customer:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    email:
                      type: string
                    type: object
                    form:
                      id:
                        type: integer
                      name:
                        type: string
                    created_at:
                      type: string
              type: object
              properties:
                pages:
                  current_page:
                    type: integer
                  next_page:
                    type: integer
                    x-nullable: true
                  previous_page:
                    type: integer
                    x-nullable: true
                  total_pages:
                    type: integer
                  total_count:
                    type: integer
    post:
      summary: Create Customer
      tags:
      - Customer
      consumes:
      - application/json
      parameters:
      - name: customer
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
              example: Kent Beck
            email:
              type: string
              example: kentbeck@gmail.com
            form_id:
              type: integer
              example: 1
          required:
          - name
          - email
      responses:
        '201':
          description: Customer Created
          schema:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
              email:
                type: string
              type: object
              form:
                id:
                  type: integer
                name:
                  type: string
              created_at:
                type: string
            required:
            - name
            - email
  "/api/forms/{id}":
    get:
      summary: Get Form
      tags:
      - Form
      consumes:
      - application/json
      parameters:
      - name: id
        in: path
        type: integer
        required: true
      responses:
        '200':
          description: Form Found
          schema:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
              type: object
              tag:
                id:
                  type: integer
                name:
                  type: string
              created_at:
                type: string
              updated_at:
                type: string
    delete:
      summary: Delete Form
      tags:
      - Form
      consumes:
      - application/json
      parameters:
      - name: id
        in: path
        type: integer
        required: true
      responses:
        '204':
          description: Form Deleted
  "/api/forms":
    get:
      summary: Get Forms
      tags:
      - Form
      consumes:
      - application/json
      responses:
        '200':
          description: Forms Found
          schema:
            type: object
            form:
              type: array
              items:
                id:
                  type: integer
                name:
                  type: string
                type: object
                tag:
                  id:
                    type: integer
                  name:
                    type: string
                created_at:
                  type: string
                updated_at:
                  type: string
    post:
      summary: Create Form
      tags:
      - Form
      consumes:
      - application/json
      parameters:
      - name: form
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
            tag_id:
              type: integer
      responses:
        '201':
          description: Form Created
          schema:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
              type: object
              tag:
                id:
                  type: integer
                name:
                  type: string
              created_at:
                type: string
              updated_at:
                type: string
  "/api/tags/{id}":
    get:
      summary: Get Tag
      tags:
      - Tag
      consumes:
      - application/json
      parameters:
      - name: id
        in: path
        type: integer
        required: true
      responses:
        '200':
          description: Tag Found
          schema:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
              created_at:
                type: string
              updated_at:
                type: string
    delete:
      summary: Delete Tag
      tags:
      - Tag
      consumes:
      - application/json
      parameters:
      - name: id
        in: path
        type: integer
        required: true
      responses:
        '204':
          description: Tag Deleted
  "/api/tags":
    get:
      summary: Get Tags
      tags:
      - Tag
      consumes:
      - application/json
      responses:
        '200':
          description: Tags Found
          schema:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
    post:
      summary: Create Tag
      tags:
      - Tag
      consumes:
      - application/json
      parameters:
      - name: tag
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
      responses:
        '201':
          description: Tag Created
          schema:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
